#!/usr/bin/env python3
"""Translate SqlOS SQL Server schema scripts into PostgreSQL counterparts."""

from __future__ import annotations

import re
from pathlib import Path

from guard_postgresql_schema import guard_missing_relations

ROOT = Path(__file__).resolve().parents[1]


def quote_brackets(sql: str) -> str:
    def repl(match: re.Match[str]) -> str:
        return '"' + match.group(1).replace("]]", "]").replace('"', '""') + '"'

    return re.sub(r"\[((?:[^\]]|\]\])+)\]", repl, sql)


def convert_types(sql: str) -> str:
    sql = re.sub(r"\bNVARCHAR\s*\(\s*MAX\s*\)", "text", sql, flags=re.I)
    sql = re.sub(r"\bVARCHAR\s*\(\s*MAX\s*\)", "text", sql, flags=re.I)
    sql = re.sub(r"\bNVARCHAR\s*\(", "varchar(", sql, flags=re.I)
    sql = re.sub(r"\bDATETIME2\b", "timestamp", sql, flags=re.I)
    sql = re.sub(r"\bUNIQUEIDENTIFIER\b", "uuid", sql, flags=re.I)
    sql = re.sub(r"\bBIT\b", "boolean", sql, flags=re.I)
    sql = re.sub(r"\bBIGINT\s+IDENTITY\s*\(\s*1\s*,\s*1\s*\)", "bigint GENERATED BY DEFAULT AS IDENTITY", sql, flags=re.I)
    sql = re.sub(r"\bINT\s+IDENTITY\s*\(\s*1\s*,\s*1\s*\)", "int GENERATED BY DEFAULT AS IDENTITY", sql, flags=re.I)
    sql = re.sub(r"\bSYSUTCDATETIME\s*\(\s*\)", "(CURRENT_TIMESTAMP AT TIME ZONE 'UTC')", sql, flags=re.I)
    sql = re.sub(r"\bGETUTCDATE\s*\(\s*\)", "(CURRENT_TIMESTAMP AT TIME ZONE 'UTC')", sql, flags=re.I)
    sql = re.sub(r"\bCREATE\s+NONCLUSTERED\s+INDEX\b", "CREATE INDEX", sql, flags=re.I)
    sql = re.sub(r"\bCREATE\s+CLUSTERED\s+INDEX\b", "CREATE INDEX", sql, flags=re.I)
    sql = re.sub(r"\bCOLLATE\s+Latin1_General_100_BIN2\b", 'COLLATE "C"', sql, flags=re.I)
    sql = re.sub(r"\bCOLLATE\s+Latin1_General_100_CI_AS\b", "", sql, flags=re.I)
    sql = re.sub(r"\bN'((?:''|[^'])*)'", lambda m: "'" + m.group(1) + "'", sql)
    sql = re.sub(r"\bDEFAULT\s+\(\s*1\s*\)", "DEFAULT TRUE", sql, flags=re.I)
    sql = re.sub(r"\bDEFAULT\s+\(\s*0\s*\)", "DEFAULT FALSE", sql, flags=re.I)
    sql = re.sub(r"\bDEFAULT\s+1\b", "DEFAULT TRUE", sql, flags=re.I)
    sql = re.sub(r"\bDEFAULT\s+0\b", "DEFAULT FALSE", sql, flags=re.I)
    sql = re.sub(r'"IsActive"\s*=\s*1\b', '"IsActive" = TRUE', sql)
    sql = re.sub(r'"IsActive"\s*=\s*0\b', '"IsActive" = FALSE', sql)
    sql = re.sub(r'"IsEnabled"\s*=\s*1\b', '"IsEnabled" = TRUE', sql)
    sql = re.sub(r'"IsEnabled"\s*=\s*0\b', '"IsEnabled" = FALSE', sql)
    return sql


def unwrap_exec(sql: str) -> str:
    return re.sub(r"EXEC\s*\(\s*N?'([\s\S]*?)'\s*\)\s*;?", lambda m: m.group(1).replace("''", "'"), sql, flags=re.I)


def convert_object_id(sql: str) -> str:
    sql = re.sub(
        r"OBJECT_ID\s*\(\s*(?:N)?'\"\{Schema\}\"\.\"([^\"]+)\"'\s*(?:,\s*(?:N)?'U')?\s*\)",
        r"to_regclass(format('%I.%I', '{Schema}', '\1'))",
        sql,
        flags=re.I,
    )
    sql = re.sub(
        r"OBJECT_ID\s*\(\s*(?:N)?'\{Schema\}\.([^']+)'\s*(?:,\s*(?:N)?'U')?\s*\)",
        r"to_regclass(format('%I.%I', '{Schema}', '\1'))",
        sql,
        flags=re.I,
    )
    sql = re.sub(
        r"COL_LENGTH\s*\(\s*(?:N)?'\"\{Schema\}\"\.\"([^\"]+)\"'\s*,\s*(?:N)?'([^']+)'\s*\)",
        r"(SELECT 1 FROM information_schema.columns WHERE table_schema = '{Schema}' AND table_name = '\1' AND column_name = '\2')",
        sql,
        flags=re.I,
    )
    sql = re.sub(
        r"COL_LENGTH\s*\(\s*(?:N)?'\{Schema\}\.([^']+)'\s*,\s*(?:N)?'([^']+)'\s*\)",
        r"(SELECT 1 FROM information_schema.columns WHERE table_schema = '{Schema}' AND table_name = '\1' AND column_name = '\2')",
        sql,
        flags=re.I,
    )
    return sql


def find_word(sql: str, word: str, start: int) -> int:
    match = re.search(rf"\b{word}\b", sql[start:], re.I)
    return -1 if not match else start + match.start()


def matching_end(sql: str, begin_at: int) -> int:
    depth = 0
    idx = begin_at
    while idx < len(sql):
        begin = find_word(sql, "BEGIN", idx)
        end = find_word(sql, "END", idx)
        if end < 0:
            return -1
        if begin >= 0 and begin < end:
            depth += 1
            idx = begin + 5
            continue
        depth -= 1
        if depth == 0:
            return end
        idx = end + 3
    return -1


def rewrite_if_blocks(sql: str) -> str:
    pieces: list[str] = []
    idx = 0
    while True:
        if_at = find_word(sql, "IF", idx)
        if if_at < 0:
            pieces.append(sql[idx:])
            break
        pieces.append(sql[idx:if_at])
        begin_at = find_word(sql, "BEGIN", if_at)
        next_if = find_word(sql, "IF", if_at + 2)
        # Single-statement IF without BEGIN
        if begin_at < 0 or (next_if >= 0 and next_if < begin_at and "\n" in sql[if_at:begin_at]):
            # take until semicolon after the IF keyword line-ish
            semi = sql.find(";", if_at)
            if semi < 0:
                pieces.append(transform_if_body(sql[if_at + 2 :].strip(), sql[if_at + 2 :].strip()))
                break
            statement = sql[if_at + 2 : semi + 1].strip()
            # strip a leading condition before CREATE/ALTER/DROP/UPDATE
            pieces.append(transform_if_body(statement, statement))
            idx = semi + 1
            continue
        end_at = matching_end(sql, begin_at)
        if end_at < 0:
            pieces.append(sql[if_at:])
            break
        condition = sql[if_at + 2 : begin_at].strip()
        body = sql[begin_at + 5 : end_at].strip()
        pieces.append(transform_if_body(condition, body))
        idx = end_at + 3
    return "".join(pieces)


def add_if_not_exists_create_table(body: str) -> str:
    return re.sub(r"\bCREATE TABLE\b", "CREATE TABLE IF NOT EXISTS", body, count=1, flags=re.I)


def add_if_not_exists_index(body: str) -> str:
    return re.sub(r"\bCREATE(\s+UNIQUE)?\s+INDEX\b", r"CREATE\1 INDEX IF NOT EXISTS", body, flags=re.I)


def add_if_not_exists_column(body: str) -> str:
    return re.sub(r"\bADD\s+(?!COLUMN\b)", "ADD COLUMN IF NOT EXISTS ", body, flags=re.I)


def transform_if_body(condition: str, body: str) -> str:
    upper = body.lstrip().upper()
    if upper.startswith("CREATE SCHEMA"):
        return 'CREATE SCHEMA IF NOT EXISTS "{Schema}";\n'
    if upper.startswith("CREATE TABLE"):
        return add_if_not_exists_index(add_if_not_exists_create_table(body)).rstrip() + ";\n"
    if upper.startswith("CREATE") and "INDEX" in upper[:40]:
        return add_if_not_exists_index(body).rstrip() + ";\n"
    if "ADD " in upper and "ALTER TABLE" in upper and "ALTER COLUMN" not in upper:
        return add_if_not_exists_column(body).rstrip() + ";\n"
    if upper.startswith("DROP INDEX"):
        body = re.sub(
            r"DROP\s+INDEX\s+(\"[^\"]+\")\s+ON\s+\"\{Schema\}\"\.\"[^\"]+\"",
            r'DROP INDEX IF EXISTS "{Schema}".\1',
            body,
            flags=re.I,
        )
        return body.rstrip() + ";\n"
    if upper.startswith("DROP CONSTRAINT") or "DROP CONSTRAINT" in upper:
        body = re.sub(r"\bDROP CONSTRAINT\b", "DROP CONSTRAINT IF EXISTS", body, flags=re.I)
        return body.rstrip() + ";\n"

    # Data / type changes: run when the leading table mentioned in the condition exists, else always.
    converted = body
    converted = re.sub(
        r"ALTER\s+TABLE\s+(\"{Schema}\"\.\"[^\"]+\")\s+ALTER\s+COLUMN\s+(\"[^\"]+\")\s+",
        r"ALTER TABLE \1 ALTER COLUMN \2 TYPE ",
        converted,
        flags=re.I,
    )
    return converted.rstrip() + ";\n"


def polish(sql: str) -> str:
    sql = re.sub(r"\bSET\s+XACT_ABORT\s+ON\s*;", "", sql, flags=re.I)
    sql = re.sub(r"\bBEGIN\s+TRY\s*", "", sql, flags=re.I)
    sql = re.sub(r"\bBEGIN\s+TRANSACTION\s*;", "", sql, flags=re.I)
    sql = re.sub(r"\bCOMMIT\s+TRANSACTION\s*;", "", sql, flags=re.I)
    sql = re.sub(r"\bEND\s+TRY[\s\S]*?END\s+CATCH", "", sql, flags=re.I)
    sql = re.sub(r"^\s*GO\s*$", "", sql, flags=re.I | re.M)
    sql = re.sub(r"IF\s+NOT\s+EXISTS\s*\(\s*SELECT\s+\*\s+FROM\s+sys\.tables[\s\S]*?\)\s*BEGIN\s*", "", sql, flags=re.I)
    sql = re.sub(r"IF\s+NOT\s+EXISTS\s*\(\s*SELECT\s+\*\s+FROM\s+sys\.columns[\s\S]*?\)\s*BEGIN\s*", "", sql, flags=re.I)
    sql = re.sub(r"IF\s+NOT\s+EXISTS\s*\(\s*SELECT\s+[1\*]\s+FROM\s+sys\.indexes[\s\S]*?\)\s*BEGIN\s*", "", sql, flags=re.I)
    sql = re.sub(r"(?:IF\s+)?NOT EXISTS\s*\(\s*SELECT\s+[1\*]\s+FROM\s+sys\.indexes[\s\S]*?\)\s*", "", sql, flags=re.I)
    sql = re.sub(r"IF\s+EXISTS\s*\(\s*SELECT\s+[1\*]\s+FROM\s+sys\.[a-z_]+\s+[\s\S]*?\)\s*BEGIN\s*", "", sql, flags=re.I)
    sql = re.sub(r"IF\s+EXISTS\s*\(\s*SELECT\s+[1\*]\s+FROM\s+sys\.[a-z_]+\s+[\s\S]*?\)\s*", "", sql, flags=re.I)
    sql = re.sub(r"to_regclass\([^)]+\)\s+IS NOT NULL AND NOT EXISTS \(SELECT 1 FROM sys\.indexes[\s\S]*?\)\s*", "", sql, flags=re.I)
    sql = re.sub(r"to_regclass\([^)]+\)\s+IS NOT NULL\s*", "", sql, flags=re.I)
    sql = re.sub(
        r"^\s*(?:IF\s+)?(?:NOT\s+)?EXISTS\s*\(\s*SELECT[\s\S]*?\)\s*$",
        "",
        sql,
        flags=re.I | re.M,
    )
    sql = re.sub(
        r"^\s*\(SELECT 1 FROM information_schema[\s\S]*?\)\s*(?:IS NULL|IS NOT NULL)\s*$",
        "",
        sql,
        flags=re.I | re.M,
    )
    sql = re.sub(r"^\s*END\s*;?\s*$", "", sql, flags=re.I | re.M)
    sql = re.sub(r"\bCREATE(\s+UNIQUE)?\s+INDEX\s+(?!IF\s+NOT\s+EXISTS)", r"CREATE\1 INDEX IF NOT EXISTS ", sql, flags=re.I)
    sql = re.sub(
        r"DROP\s+INDEX\s+(\"[^\"]+\")\s+ON\s+\"\{Schema\}\"\.\"[^\"]+\"",
        r'DROP INDEX IF EXISTS "{Schema}".\1',
        sql,
        flags=re.I,
    )
    sql = re.sub(
        r'ALTER\s+TABLE\s+("[^"]+"\."[^\"]+")\s+ALTER\s+COLUMN\s+("[^"]+")\s+(?!TYPE\b|SET\b|DROP\b)',
        r"ALTER TABLE \1 ALTER COLUMN \2 TYPE ",
        sql,
        flags=re.I,
    )
    sql = re.sub(
        r'UPDATE ("\{Schema\}"\."SqlOSSchema") SET "Version" = (\d+);\s*INSERT INTO \1 \("Version"\) VALUES \(\2\);',
        r'UPDATE \1 SET "Version" = \2;\nINSERT INTO \1 ("Version") SELECT \2 WHERE NOT EXISTS (SELECT 1 FROM \1);',
        sql,
        flags=re.I,
    )
    sql = re.sub(r'"IsEnabled"\s*=\s*1\b', '"IsEnabled" = TRUE', sql)
    sql = re.sub(r'"IsEnabled"\s*=\s*0\b', '"IsEnabled" = FALSE', sql)
    sql = re.sub(r";;+", ";", sql)
    sql = re.sub(r"\n{3,}", "\n\n", sql)
    return sql


def convert_delete_cte(sql: str) -> str:
    pattern = re.compile(
        r";?WITH\s+(\w+)\s+AS\s*\(\s*"
        r"(SELECT\s+\"Id\",?\s+ROW_NUMBER\(\)\s+OVER\s*\((.*?)\)\s+AS\s+rowNumber\s+"
        r"FROM\s+(\"{Schema}\"\.\"[^\"]+\")(.*?))\)\s*"
        r"DELETE\s+FROM\s+\1\s+WHERE\s+rowNumber\s*>\s*1;",
        flags=re.I | re.S,
    )

    def repl(match: re.Match[str]) -> str:
        window = match.group(3).strip()
        table = match.group(4)
        extra = match.group(5).strip()
        where = f"\n    {extra}" if extra else ""
        return (
            f'DELETE FROM {table}\n'
            f'WHERE "Id" IN (\n'
            f'    SELECT "Id" FROM (\n'
            f'        SELECT "Id", ROW_NUMBER() OVER ({window}) AS rowNumber\n'
            f'        FROM {table}{where}\n'
            f'    ) ranked\n'
            f'    WHERE rowNumber > 1\n'
            f');\n'
        )

    return pattern.sub(repl, sql)


def translate(sql: str) -> str:
    sql = unwrap_exec(sql)
    sql = convert_types(sql)
    sql = quote_brackets(sql)
    sql = convert_object_id(sql)
    sql = rewrite_if_blocks(sql)
    sql = polish(sql)
    sql = convert_delete_cte(sql)
    sql = guard_missing_relations(sql)
    return (
        "-- PostgreSQL translation of the matching SQL Server script.\n"
        "-- CREATE/ALTER statements are idempotent via IF NOT EXISTS.\n"
        "-- Statements that target a missing table are skipped, matching SQL Server OBJECT_ID guards.\n"
        + sql.strip()
        + "\n"
    )


def translate_tree(source: Path, dest: Path) -> None:
    dest.mkdir(parents=True, exist_ok=True)
    for path in sorted(source.glob("*.sql")):
        dest.joinpath(path.name).write_text(translate(path.read_text()), encoding="utf-8")


HAND_AUTHORED = {
    "007_HeadlessAuth.sql",
    "028_SigningKeyCustody.sql",
    "030_ScimDirectorySyncHardening.sql",
    "034_ConfigurationOwnership.sql",
    "035_ApplicationAssignmentOwnership.sql",
    "036_SamlConnectionOwnership.sql",
    "038_ScopedAuditIdempotency.sql",
    "042_AuthPageBrandingOwnership.sql",
    "007_MachineClientOwnership.sql",
}


def main() -> None:
    translate_tree(ROOT / "src/SqlOS/AuthServer/Schema/SqlServer", ROOT / "src/SqlOS/AuthServer/Schema/PostgreSql")
    translate_tree(ROOT / "src/SqlOS/Fga/Schema/SqlServer", ROOT / "src/SqlOS/Fga/Schema/PostgreSql")
    print("translated", len(list((ROOT / "src/SqlOS/AuthServer/Schema/PostgreSql").glob("*.sql"))), "auth scripts")
    print("translated", len(list((ROOT / "src/SqlOS/Fga/Schema/PostgreSql").glob("*.sql"))), "fga scripts")
    print("hand-authored files must be restored after translate:", ", ".join(sorted(HAND_AUTHORED)))


if __name__ == "__main__":
    main()
