using System.Data.Common;
using System.Globalization;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Npgsql;
using SqlOS.Fga.Configuration;

namespace SqlOS.Database;

internal sealed partial class PostgreSqlDatabaseProvider : ISqlOSDatabaseProvider
{
    public static PostgreSqlDatabaseProvider Instance { get; } = new();

    public SqlOSDatabaseProviderKind Kind => SqlOSDatabaseProviderKind.PostgreSql;
    public string EfProviderName => SqlOSDatabase.PostgreSqlProviderName;
    public string DisplayName => "PostgreSQL";
    public string AuthMigrationResourcePrefix => "SqlOS.AuthServer.Schema.PostgreSql.";
    public string FgaMigrationResourcePrefix => "SqlOS.Fga.Schema.PostgreSql.";
    public string MaxStringStoreType => "text";

    public string QuoteIdentifier(string identifier)
        => "\"" + identifier.Replace("\"", "\"\"", StringComparison.Ordinal) + "\"";

    public string Qualify(string schema, string name)
        => $"{QuoteIdentifier(schema)}.{QuoteIdentifier(name)}";

    public string FilteredIndexIsNotNull(string column) => $"{QuoteIdentifier(column)} IS NOT NULL";
    public string FilteredIndexEqualsTrue(string column) => $"{QuoteIdentifier(column)} = TRUE";

    public IReadOnlyList<string> SplitBatches(string sql)
        => string.IsNullOrWhiteSpace(sql) ? [] : [sql];

    public DbParameter CreateParameter(string name, object? value)
        => new NpgsqlParameter(name, value ?? DBNull.Value);

    public string BuildEnsureAuthVersionTablesSql(string schema)
    {
        var quoted = QuoteIdentifier(schema);
        var versions = Qualify(schema, "SqlOSSchema");
        var applied = Qualify(schema, "SqlOSAppliedMigrations");
        return $"""
            CREATE SCHEMA IF NOT EXISTS {quoted};
            CREATE TABLE IF NOT EXISTS {versions} ("Version" INT NOT NULL);
            CREATE TABLE IF NOT EXISTS {applied} (
                "Sequence" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                "ScriptName" varchar(450) NOT NULL,
                "Version" INT NOT NULL,
                "AppliedAt" timestamp NOT NULL,
                CONSTRAINT "PK_SqlOSAppliedMigrations" PRIMARY KEY ("ScriptName"),
                CONSTRAINT "UX_SqlOSAppliedMigrations_Sequence" UNIQUE ("Sequence")
            );
            """;
    }

    public string BuildSelectVersionSql(string schema)
        => $"SELECT \"Version\" FROM {Qualify(schema, "SqlOSSchema")} LIMIT 1";

    public string BuildSelectAppliedMigrationsSql(string schema)
        => $"SELECT \"ScriptName\" FROM {Qualify(schema, "SqlOSAppliedMigrations")}";

    public string BuildRecordAppliedMigrationSql(string schema)
        => $"""
            INSERT INTO {Qualify(schema, "SqlOSAppliedMigrations")} ("ScriptName", "Version", "AppliedAt")
            SELECT @scriptName, @version, (CURRENT_TIMESTAMP AT TIME ZONE 'UTC')
            WHERE NOT EXISTS (
                SELECT 1 FROM {Qualify(schema, "SqlOSAppliedMigrations")} WHERE "ScriptName" = @scriptName);
            """;

    public string BuildUpdateVersionSql(string schema)
        => $"UPDATE {Qualify(schema, "SqlOSSchema")} SET \"Version\" = @targetVersion";

    public string BuildEnsureFgaVersionTableSql(string schema)
        => $"""
            CREATE SCHEMA IF NOT EXISTS {QuoteIdentifier(schema)};
            CREATE TABLE IF NOT EXISTS {Qualify(schema, "SqlOSFgaSchema")} ("Version" INT NOT NULL);
            """;

    public string BuildSelectFgaVersionSql(string schema)
        => $"SELECT \"Version\" FROM {Qualify(schema, "SqlOSFgaSchema")} LIMIT 1";

    public string BuildLockedSelectSql(string schema, string table, string whereSql, string? orderBySql = null)
    {
        var sql = $"SELECT * FROM {Qualify(schema, table)} WHERE {whereSql}";
        if (!string.IsNullOrWhiteSpace(orderBySql))
        {
            sql += $" ORDER BY {orderBySql}";
        }

        return sql + " FOR UPDATE";
    }

    public string BuildIsResourceAccessibleFunctionSql(SqlOSFgaOptions options)
    {
        ArgumentNullException.ThrowIfNull(options);
        var schema = QuoteIdentifier(options.Schema);
        var tables = options.TableNames;
        var resources = Qualify(options.Schema, tables.Resources);
        var grants = Qualify(options.Schema, tables.Grants);
        var rolePermissions = Qualify(options.Schema, tables.RolePermissions);
        var subjects = Qualify(options.Schema, tables.Subjects);
        var users = Qualify(options.Schema, tables.Users);
        var serviceAccounts = Qualify(options.Schema, tables.ServiceAccounts);
        var userGroups = Qualify(options.Schema, tables.UserGroups);
        var agents = Qualify(options.Schema, tables.Agents);
        var permissions = Qualify(options.Schema, tables.Permissions);
        var maxDepth = Math.Max(1, options.MaxResourceHierarchyDepth)
            .ToString(CultureInfo.InvariantCulture);
        return $"""
            CREATE OR REPLACE FUNCTION {schema}."fn_IsResourceAccessible"(
                p_resource_id varchar(128),
                p_subject_ids text,
                p_permission_id varchar(128)
            )
            RETURNS TABLE("Id" varchar(450))
            LANGUAGE sql
            STABLE
            AS $sqlos$
            WITH RECURSIVE ancestors AS (
                SELECT
                    "Id",
                    "ParentId",
                    0 AS "Depth",
                    ('|' || "Id" || '|')::text AS "VisitedPath",
                    FALSE AS "CycleDetected"
                FROM {resources}
                WHERE "Id" = p_resource_id AND "IsActive" = TRUE

                UNION ALL

                SELECT
                    r."Id",
                    r."ParentId",
                    a."Depth" + 1,
                    (a."VisitedPath" || r."Id" || '|')::text,
                    (strpos(a."VisitedPath", '|' || r."Id" || '|') > 0)
                FROM {resources} r
                INNER JOIN ancestors a ON r."Id" = a."ParentId"
                WHERE a."Depth" < {maxDepth}
                  AND a."CycleDetected" = FALSE
                  AND r."IsActive" = TRUE
            )
            SELECT a."Id"
            FROM ancestors a
            INNER JOIN {grants} g ON a."Id" = g."ResourceId"
            INNER JOIN {rolePermissions} rp ON g."RoleId" = rp."RoleId"
            INNER JOIN {subjects} s ON g."SubjectId" = s."Id"
            LEFT JOIN {users} u ON s."Id" = u."SubjectId"
            LEFT JOIN {serviceAccounts} sa ON s."Id" = sa."SubjectId"
            LEFT JOIN {userGroups} ug ON s."Id" = ug."SubjectId"
            LEFT JOIN {agents} ag ON s."Id" = ag."SubjectId"
            WHERE g."SubjectId" IN (SELECT jsonb_array_elements_text(p_subject_ids::jsonb))
              AND rp."PermissionId" = p_permission_id
              AND NOT EXISTS (SELECT 1 FROM ancestors malformed WHERE malformed."CycleDetected" = TRUE)
              AND NOT EXISTS (
                  SELECT 1
                  FROM ancestors truncated
                  WHERE truncated."Depth" = {maxDepth}
                    AND truncated."ParentId" IS NOT NULL
              )
              AND EXISTS (
                  SELECT 1
                  FROM {resources} target
                  INNER JOIN {permissions} permission ON permission."Id" = p_permission_id
                  WHERE target."Id" = p_resource_id
                    AND (permission."ResourceTypeId" IS NULL OR permission."ResourceTypeId" = target."ResourceTypeId")
              )
              AND (s."SubjectTypeId" <> 'user' OR u."IsActive" = TRUE)
              AND (s."SubjectTypeId" <> 'service_account' OR (sa."SubjectId" IS NOT NULL AND (sa."ExpiresAt" IS NULL OR sa."ExpiresAt" > (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'))))
              AND (s."SubjectTypeId" <> 'group' OR ug."IsActive" = TRUE)
              AND (s."SubjectTypeId" <> 'agent' OR ag."SubjectId" IS NOT NULL)
              AND EXISTS (
                  SELECT 1
                  FROM {subjects} caller
                  LEFT JOIN {users} callerUser ON caller."Id" = callerUser."SubjectId"
                  LEFT JOIN {serviceAccounts} callerSa ON caller."Id" = callerSa."SubjectId"
                  LEFT JOIN {userGroups} callerGroup ON caller."Id" = callerGroup."SubjectId"
                  LEFT JOIN {agents} callerAgent ON caller."Id" = callerAgent."SubjectId"
                  WHERE caller."Id" = (p_subject_ids::jsonb ->> 0)
                    AND (caller."SubjectTypeId" <> 'user' OR callerUser."IsActive" = TRUE)
                    AND (caller."SubjectTypeId" <> 'service_account' OR (callerSa."SubjectId" IS NOT NULL AND (callerSa."ExpiresAt" IS NULL OR callerSa."ExpiresAt" > (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'))))
                    AND (caller."SubjectTypeId" <> 'group' OR callerGroup."IsActive" = TRUE)
                    AND (caller."SubjectTypeId" <> 'agent' OR callerAgent."SubjectId" IS NOT NULL)
              )
              AND (g."EffectiveFrom" IS NULL OR g."EffectiveFrom" <= (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'))
              AND (g."EffectiveTo" IS NULL OR g."EffectiveTo" >= (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'))
            LIMIT 1
            $sqlos$;
            """;
    }

    public async Task AcquireTransactionLockAsync(
        DatabaseFacade database,
        string resource,
        TimeSpan timeout,
        string failureMessage,
        CancellationToken cancellationToken)
    {
        var timeoutMs = Math.Max(1, (int)timeout.TotalMilliseconds);
        try
        {
            await database.ExecuteSqlRawAsync(
                $"""
                SET LOCAL lock_timeout = '{timeoutMs}ms';
                SELECT pg_advisory_xact_lock(
                    ('x' || substr(md5(@resource), 1, 8))::bit(32)::int,
                    ('x' || substr(md5(@resource), 9, 8))::bit(32)::int);
                """,
                [CreateParameter("@resource", resource)],
                cancellationToken);
        }
        catch (Exception ex) when (ex is PostgresException { SqlState: PostgresErrorCodes.LockNotAvailable or "57014" })
        {
            throw new InvalidOperationException(failureMessage, ex);
        }
    }
}
